eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka:8300/eureka/
    instance:
      preferIpAddress: true
      hostname: localhost