spring:
  application:
    name: eureka

server:
  port: 8300

eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka:${server.port}/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: http://db-service:8301
    stock-service:
      path: /products-service/**
      url: http://localhost:8302
